apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: your-namespace
  namespace: guestbook
  annotations:
    kubernetes.io/ingress.class: "nginx"
spec:
  rules:
  - host: up2you.app00.kubeworkshop.inet.co.th
    http:
      paths:
      - backend:
          serviceName: frontend
          servicePort: 80
